// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbPy9jx3Lw5mi2LJQeCgsG-r0oOfzG2bU',
    appId: '1:496726740044:android:4300ceaff6f3654b6fb8e9',
    messagingSenderId: '496726740044',
    projectId: 'ecoeats-4f19c',
    storageBucket: 'ecoeats-4f19c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGaCKJviRURoQR0bj0b_SG4h-CrAcM4Rc',
    appId: '1:496726740044:ios:a696017f72aee38c6fb8e9',
    messagingSenderId: '496726740044',
    projectId: 'ecoeats-4f19c',
    storageBucket: 'ecoeats-4f19c.firebasestorage.app',
    androidClientId: '496726740044-cplk2rf6jk6ct9n37v6brppk3jkucu00.apps.googleusercontent.com',
    iosClientId: '496726740044-9sqprlcdm5tic0knnj8sncfkb27pfgh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
